#!/bin/bash

set -u

function generate_isolinux_cfg() {
    sudo tee $ISOLINUX_CFG <<EOF
UI vesamenu.c32

MENU TITLE Boot Menu
DEFAULT linux
TIMEOUT 600
MENU RESOLUTION 640 480
MENU COLOR border       30;44   #40ffffff #a0000000 std
MENU COLOR title        1;36;44 #9033ccff #a0000000 std
MENU COLOR sel          7;37;40 #e0ffffff #20ffffff all
MENU COLOR unsel        37;44   #50ffffff #a0000000 std
MENU COLOR help         37;40   #c0ffffff #a0000000 std
MENU COLOR timeout_msg  37;40   #80ffffff #00000000 std
MENU COLOR timeout      1;37;40 #c0ffffff #00000000 std
MENU COLOR msg07        37;40   #90ffffff #a0000000 std
MENU COLOR tabmsg       31;40   #30ffffff #00000000 std

LABEL linux
  MENU LABEL deepin Live [BIOS/ISOLINUX]
  MENU DEFAULT
  KERNEL /live/vmlinuz
  APPEND initrd=/live/initrd boot=live

LABEL linux
  MENU LABEL deepin Live [BIOS/ISOLINUX] (nomodeset)
  MENU DEFAULT
  KERNEL /live/vmlinuz
  APPEND initrd=/live/initrd boot=live nomodeset"
EOF
}

function generate_grub_cfg() {
    sudo tee $GRUB_CFG <<EOF
search --set=root --label deepin

set default="0"
set timeout=30

# If X has issues finding screens, experiment with/without nomodeset.

menuentry 'deepin Live [EFI/GRUB]' {
    insmod all_video
    set gfxpayload=keep
    linux (\$root)/live/vmlinuz boot=live union=overlay locales=$LOCALES console=tty splash --
    initrd (\$root)/live/initrd
}

menuentry 'deepin Live [EFI/GRUB] (nomodeset)' {
    insmod all_video
    set gfxpayload=keep
    linux (\$root)/live/vmlinuz boot=live union=overlay locales=$LOCALES console=tty splash -- nomodeset
    initrd (\$root)/live/initrd
}
EOF
}

function generate_grub_standalone_cfg() {
    sudo tee $GRUB_STANDALONE_CFG <<EOF
search --set=root --label deepin
set prefix=(\$root)/boot/grub/
configfile /boot/grub/grub.cfg
EOF
}

export -f generate_isolinux_cfg generate_grub_cfg generate_grub_standalone_cfg